### ISSUE TITLE
Is the plugin open sourced? 

### ISSUE THREAD

**Issue by Colorfulstan** [overwolf/experimental-plugin#1]
I don't see the plugin in the overwolf plugins repository.
Is it possible to add it or do you think there is no need for that?

I currently don't have the need to go into it, just curious :)

@eransharv

**Comment by tomwolfgang** [comment]
No longer relevant, as you can get this from the overwolf.utils.getSystemInformation (HAGSEnabled).
I'll ask Eran to update both this repo and the documentations - unless you don't mind adding it yourself to our docs :)

**Comment by eransharv** [comment]
@tomwolfgang @Colorfulstan I updated the docs.

* https://overwolf.github.io/docs/topics/video-capture#windows-10-hardware-accelerated-gpu-scheduling-notice
* https://overwolf.github.io/docs/api/overwolf-utils#getsysteminformationresult-object
